dna = input("=== Анализ последовательности ДНК ===\nВведите последовательность ДНК: ").upper()
count_A = dna.count("A")
count_T = dna.count("T")
count_G = dna.count("G")
count_C = dna.count("C")
dna_length = len(dna)
print(f"Последовательность в верхнем регистре: {dna}")
print("Подсчёт нуклеотидов:")
print(f"A: {count_A}")
print(f"T: {count_T}")
print(f"G: {count_G}")
print(f"C: {count_C}")
print(f"Общая длина: {dna_length} нуклеотидов")