researcher_name = input("Введите ФИО исследователя: ")
date = input("Введите дату: ")
experiment_name = input("Введите название эксперимента: ")
conclusion = input("Сделайте вывод по эксперименту: ")
with open("journal.txt", "w", encoding="utf-8") as report:
    report.write(f"+--------------------------------------------------+\n")
    report.write(f"|  Электронный лабораторный журнал                 |\n")
    report.write(f"+--------------------------------------------------+\n")
    report.write(f"| ФИО исследователя: {researcher_name}          |\n")
    report.write(f"| Дата: {date}                                 |\n")
    report.write(f"| Эксперимент: {experiment_name}           |\n")
    report.write(f"+--------------------------------------------------+\n")
    report.write(f"| Вывод: {conclusion}  |\n")
    report.write(f"+--------------------------------------------------+")